/**
 * Auld Lang Syne - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `auld-lang-syne.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const AULD_LANG_SYNE: ScoreJSON = {
  id: 'auld-lang-syne',
  title: 'Auld Lang Syne',
  composer: 'tradicional escocesa; letra de Robert Burns (1788)',
  collection: 'ballads',
  timeSignature: [4, 4],
  pickupBeats: 1,
  key: { tonic: 'G', mode: 'major' },
  tempo: 84,
  toleranceCents: 35,
  source: {
    pitches: 'Tablatura de 6 furos "Auld Lang Syne.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (100% de casamento de altura com a tab)',
    referenceName: 'Wikipédia (en) "Auld Lang Syne", partitura Lilypond, que cita Steele 1905',
    referenceUrl: 'https://en.wikipedia.org/wiki/Auld_Lang_Syne',
    rhythmMatch: 1,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1, section: 'Verso' },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 3 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 3 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1.5, section: 'Refrão' },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 3 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 3 },
  ],
};
