/**
 * Brian Boru's March - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `brian-boru-s-march.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const BRIAN_BORU: ScoreJSON = {
  id: 'brian-boru',
  title: 'Brian Boru\'s March',
  collection: 'irish',
  pitchReference: 'whistle',
  timeSignature: [6, 8],
  pickupBeats: 1,
  key: { tonic: 'E', mode: 'minor' },
  tempo: 116,
  toleranceCents: 30,
  source: {
    pitches: 'Tablatura de 6 furos "Brian Boru\'s March.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (94% de casamento de altura com a tab)',
    referenceName: 'Brian Boru\'s March (setting 52311, por Martial)',
    referenceUrl: 'https://thesession.org/tunes/271#setting52311',
    rhythmMatch: 0.94,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: null, beats: 0.5 },
  ],
};
