/**
 * Danza del Oso - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `danza-del-oso.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const DANZA_DEL_OSO: ScoreJSON = {
  id: 'danza-del-oso',
  title: 'Danza del Oso',
  collection: 'ballads',
  timeSignature: [2, 4],
  pickupBeats: 1,
  key: { tonic: 'E', mode: 'minor' },
  tempo: 128,
  toleranceCents: 30,
  source: {
    pitches: 'Tablatura de 6 furos "Danza del Oso.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (96% de casamento de altura com a tab)',
    referenceName: 'Bear Dance, The (setting 28850, por Beleragor)',
    referenceUrl: 'https://thesession.org/tunes/4195#setting28850',
    rhythmMatch: 0.96,
  },
  irregularMeasures: [4, 19],
  warnings: [
    'compasso 5: soma 3 tempos, esperado 2',
  ],
  events: [
    { pitch: null, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: null, beats: 0.5 },
    { pitch: null, beats: 0.5 },
  ],
};
