/**
 * Drunken Sailor - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `drunken-sailor.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const DRUNKEN_SAILOR: ScoreJSON = {
  id: 'drunken-sailor',
  title: 'Drunken Sailor',
  collection: 'irish',
  pitchReference: 'whistle',
  timeSignature: [4, 4],
  pickupBeats: 2,
  key: { tonic: 'E', mode: 'dorian' },
  tempo: 108,
  toleranceCents: 30,
  source: {
    pitches: 'Tablatura de 6 furos "Drunken Sailor.jpg" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (96% de casamento de altura com a tab)',
    referenceName: 'Drunken Sailor (setting 56633, por Doows)',
    referenceUrl: 'https://thesession.org/tunes/15961#setting56633',
    rhythmMatch: 0.96,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 3.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: null, beats: 0.5 },
  ],
};
