/**
 * Greensleeves - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `greensleeves.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const GREENSLEEVES: ScoreJSON = {
  id: 'greensleeves',
  title: 'Greensleeves',
  collection: 'ballads',
  timeSignature: [6, 8],
  pickupBeats: 0.5,
  key: { tonic: 'B', mode: 'minor' },
  tempo: 96,
  toleranceCents: 30,
  source: {
    pitches: 'Tablatura de 6 furos "Greensleeves.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (83% de casamento de altura com a tab)',
    referenceName: 'Greensleeves',
    referenceUrl: 'https://fr.wikipedia.org/wiki/Greensleeves',
    rhythmMatch: 0.83,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.75 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.25 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.75 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.25 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.75 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.25 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.25 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 0.75 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.25 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 0.75 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.25 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.75 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.25 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: null, beats: 0.5 },
  ],
};
