/**
 * Inisheer - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `ABC em tools/partituras-import/abc_tunes.py` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const INISHEER: ScoreJSON = {
  id: 'inisheer',
  title: 'Inisheer',
  composer: 'Tommy Walsh',
  collection: 'irish',
  timeSignature: [3, 4],
  pickupBeats: 1,
  key: { tonic: 'G', mode: 'major' },
  tempo: 90,
  toleranceCents: 35,
  source: {
    pitches: 'ABC de sessão do thesession.org (altura e ritmo da mesma fonte)',
    rhythm: 'ritmo do próprio ABC - não há tab para decodificar nem duração a transferir',
    referenceName: 'Inisheer (setting 20740, por Tommy Walsh)',
    referenceUrl: 'https://thesession.org/tunes/211#setting20740',
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 3 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 3 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 3 },
  ],
};
