/**
 * Molly Malone - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `molly-malone.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const MOLLY_MALONE: ScoreJSON = {
  id: 'molly-malone',
  title: 'Molly Malone',
  collection: 'irish',
  pitchReference: 'whistle',
  timeSignature: [3, 4],
  pickupBeats: 2.5,
  key: { tonic: 'D', mode: 'major' },
  tempo: 90,
  toleranceCents: 35,
  source: {
    pitches: 'Tablatura de 6 furos "Molly Malone.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (82% de casamento de altura com a tab)',
    referenceName: 'Cockles And Mussels (setting 43301, por Sliabh)',
    referenceUrl: 'https://thesession.org/tunes/12844#setting43301',
    rhythmMatch: 0.82,
  },
  irregularMeasures: [],
  warnings: [
    'compasso 19: soma 2 tempos, esperado 3 ou 0.5',
  ],
  events: [
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
  ],
};
