/**
 * The Rattlin' Bog - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `rattling-bog.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const RATTLIN_BOG: ScoreJSON = {
  id: 'rattlin-bog',
  title: 'The Rattlin\' Bog',
  collection: 'irish',
  timeSignature: [2, 4],
  pickupBeats: 1,
  key: { tonic: 'G', mode: 'major' },
  tempo: 128,
  toleranceCents: 30,
  source: {
    pitches: 'Tablatura de 6 furos "Rattling Bog.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (93% de casamento de altura com a tab)',
    referenceName: 'Rattlin\' Bog, The (setting 47481, por NfldWhistler)',
    referenceUrl: 'https://thesession.org/tunes/583#setting47481',
    rhythmMatch: 0.93,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
  ],
};
