/**
 * Scarborough Fair - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `scarborough-fair.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const SCARBOROUGH: ScoreJSON = {
  id: 'scarborough',
  title: 'Scarborough Fair',
  collection: 'ballads',
  timeSignature: [3, 4],
  pickupBeats: 2,
  key: { tonic: 'E', mode: 'dorian' },
  tempo: 90,
  toleranceCents: 35,
  source: {
    pitches: 'Tablatura de 6 furos "Scarborough Fair.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (92% de casamento de altura com a tab)',
    referenceName: 'Scarborough Fair (setting 7522, por MBAC)',
    referenceUrl: 'https://thesession.org/tunes/7522#setting7522',
    rhythmMatch: 0.92,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 2 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'C', alter: 1, octave: 5 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 2 },
    { pitch: { step: 'E', alter: 0, octave: 5 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 2 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
  ],
};
