/**
 * The Skye Boat Song - partitura do repertório do Treino.
 *
 * GERADO por `tools/partituras-import/import_scores.py` a partir de
 * `skye-boat-song.json` - não editar à mão.
 */
import type { ScoreJSON } from '../score';

export const SKYE_BOAT_SONG: ScoreJSON = {
  id: 'skye-boat-song',
  title: 'The Skye Boat Song',
  collection: 'ballads',
  pitchReference: 'whistle',
  timeSignature: [3, 4],
  pickupBeats: 0,
  key: { tonic: 'G', mode: 'major' },
  tempo: 90,
  toleranceCents: 35,
  source: {
    pitches: 'Tablatura de 6 furos "Skye Boat Song.pdf" (whistle em Ré), decodificada por imagem',
    rhythm: 'ritmo transferido da referência (89% de casamento de altura com a tab)',
    referenceName: 'Skye Boat Song, The (setting 16682, por ceolachan)',
    referenceUrl: 'https://thesession.org/tunes/3690#setting16682',
    rhythmMatch: 0.89,
  },
  irregularMeasures: [],
  events: [
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'D', alter: 0, octave: 5 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'B', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'A', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 0.5 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 1 },
    { pitch: { step: 'G', alter: 0, octave: 4 }, beats: 2 },
    { pitch: { step: 'F', alter: 1, octave: 4 }, beats: 0.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'E', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
    { pitch: { step: 'D', alter: 0, octave: 4 }, beats: 2.5 },
    { pitch: null, beats: 0.5 },
  ],
};
